// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMJ0vlTpUvnP2r9ehBiXbieqcrmuTJghw',
    appId: '1:910917613796:web:f8c98b2408c618bd8c94f1',
    messagingSenderId: '910917613796',
    projectId: 'almostzenly-45f5f',
    authDomain: 'almostzenly-45f5f.firebaseapp.com',
    storageBucket: 'almostzenly-45f5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD55SzmYiThOwEjnsKeYjHQ964aBRHHc-E',
    appId: '1:910917613796:android:7e3a9fd4e4d37cca8c94f1',
    messagingSenderId: '910917613796',
    projectId: 'almostzenly-45f5f',
    storageBucket: 'almostzenly-45f5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrS2P5HjKY9U2cdJcRVZOLrhS8-NJB7bI',
    appId: '1:910917613796:ios:40f97c5bc7922a828c94f1',
    messagingSenderId: '910917613796',
    projectId: 'almostzenly-45f5f',
    storageBucket: 'almostzenly-45f5f.appspot.com',
    iosBundleId: 'com.obashun22.almostzenly',
  );
}
